### DISCUSSION TITLE
Empty dumps

### DISCUSSION THREAD

**Discussion by fersarr** [prodrigestivill/docker-postgres-backup-local#106] [Q&A] [answered]
Hi. This might be a missconfiguration, probably something I did wrong, but I don't really know what else to try and the logs from pg_backup suggest that everything is fine while the dumps are empty. Any help would be appreaciated.

The dumps:
```

--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 13.0 (Debian 13.0-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: myuser
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO myuser;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: myuser
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- PostgreSQL database dump complete
--
```

The pg_dumper says:
```
pg_backup_container | 2020/11/11 11:45:56 61: SQL backup created successfully
pg_backup_container | 2020/11/11 11:46:56 77 cmd: /backup.sh
pg_backup_container | 2020/11/11 11:46:56 77: Creating dump of mydbname database from db...
pg_backup_container | 2020/11/11 11:46:56 77: '/backups/weekly/mydbname-202046.sql.gz' => '/backups/daily/feedfeedbackdb-20201111-114656.sql.gz'
pg_backup_container | 2020/11/11 11:46:56 77: '/backups/monthly/mydbname-202011.sql.gz' => '/backups/daily/feedfeedbackdb-20201111-114656.sql.gz'
pg_backup_container | 2020/11/11 11:46:56 77: Cleaning older than 7 days for mydbname database from db...
pg_backup_container | 2020/11/11 11:46:56 77: SQL backup created successfully
```

The database actually has data, it is supporting a website that is in use.

Here's the docker-compose:

```
  db:
    image: postgres:12-alpine
    container_name: postgres_container_feedfeedback
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydbname
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypw123
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgbackups:
    # https://github.com/prodrigestivill/docker-postgres-backup-local
    container_name: pg_backup_container
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./pg_backup:/backups
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=mydbname
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypw123
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 0h1m00s  # @daily  # @every 0h30m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
      - POSTGRES_PORT=5432  # must match the db port
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
```
