### DISCUSSION TITLE
Error when launch manual backup

### DISCUSSION THREAD

**Discussion by JoDrm** [prodrigestivill/docker-postgres-backup-local#115] [Q&A] [answered]
Hello,

I have a problem when launching the container, I don't know if it started completely because no backup is created even manually.

I only have logs that appear when launching :

> 2022/08/24 15:23:40 Running version: v0.0.10
> 2022/08/24 15:23:40 new cron: @daily
> 2022/08/24 15:23:40 Opening port 8080 for health checking

Moreover, when I connect to this container and launch a manual backup with the` sh backup.sh` command, it returns an error: 

> backup.sh: 2: set: Illegal option -o pipefail

My setup is as follows:

```
  pgbackups:
     image: prodrigestivill/postgres-backup-local
     restart: always
     user: postgres:postgres
     volumes:
        - /home/docker/pgbackups_dev:/backups
     environment:
        - TZ="Europe/Paris"
        - POSTGRES_HOST=db-v2
        - POSTGRES_DB=plop
        - POSTGRES_USER=****
        - POSTGRES_PASSWORD=****
        - SCHEDULE=@daily
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080
     networks:
        - db-v2-network
```

Did I miss something during setup?
