### ISSUE TITLE
BACKUP_KEEP_****=0 behaviour

### ISSUE THREAD

**Issue by lordraiden** [prodrigestivill/docker-postgres-backup-local#141]
I have this variables set to 0

BACKUP_KEEP_WEEKS | Number of weekly backups to keep before removal. Defaults to 4.

BACKUP_KEEP_MONTHS | Number of monthly backups to keep before removal. Defaults to 6.

 ```
 pgbackups:
    container_name: Immich_pgbackups  
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    user: postgres:postgres # Optional: see below
    networks:
      - immich_network    
    volumes:
      - /mnt/user/Docker/Immich/pgbackups:/backups
    links:
      - database
    depends_on:
      - database
    environment:
      - TZ
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
     #- POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      - POSTGRES_EXTRA_OPTS=-Z6
      - SCHEDULE=30 1 */3 * * #At 01:30 AM, every 3 days
      - BACKUP_KEEP_DAYS=6
      - BACKUP_KEEP_WEEKS=1
      - BACKUP_KEEP_MONTHS=0
      - HEALTHCHECK_PORT=5432
```
But I still get monthy backups stored, is there a way to configure this only to keep 6 days of backup? not weekly not monthly?
