### ISSUE TITLE
Add a env variable to make latest a hard copy

### ISSUE THREAD

**Issue by fredericoschardong** [prodrigestivill/docker-postgres-backup-local#151]
Symlinks are interesting to save space. However, I would like to have a volume in my postgress container to restore the latest backup in case I have to remove the postgres container and its volume for some reason.  E.g.:

```
  db:
    image: bitnami/postgresql:14.11.0
    restart: always
    volumes:
      - BACKUP_DIR/last/DB-latest.sql.gz: /docker-entrypoint-initdb.d/backup.sql.gz:ro
```

Can we have a env variable to ensure `latest.sql.gz` is a hard copy instead of a symlink?
