### ISSUE TITLE
BACKUP_ON_START doesn't seem to work

### ISSUE THREAD

**Issue by TiraelSedai** [prodrigestivill/docker-postgres-backup-local#159]
Here's part of my compose:
```
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      BACKUP_ON_START: TRUE
    volumes:
      - D:/Immich/db_dumps:/backups
    depends_on:
      - database
```
and here are the logs after start:
```
2024-09-16 12:55:40 2024/09/16 09:55:40 Running version: v0.0.11
2024-09-16 12:55:40 2024/09/16 09:55:40 new cron: @daily
2024-09-16 12:55:40 2024/09/16 09:55:40 Opening port 8080 for health checking
```
