### ISSUE TITLE
Backup no longer working, no errors or messages logged

### ISSUE THREAD

**Issue by Altycoder** [prodrigestivill/docker-postgres-backup-local#167]
This backup image/container has been working quite nicely for me for 6-9 months performing daily backups, but no longer works and nothing is printed to the log I can see in portainer so I'm not sure how to diagnose.  I'm wondering whether the move to immich v129.0 has changed something in postgres?  I've added 'VALIDATE_ON_START=TRUE' and 'BACKUP_ON_START=TRUE' to the environment variables and recreated the container to try and force some log messages but it's silently not doing anything.

Full immich stack compose is below:

```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    networks:
      - immich
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - immich
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1    
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    restart: always
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on

#https://immich.app/docs/administration/backup-and-restore/
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    user: postgres:postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_CLUSTER='TRUE'
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - SCHEDULE="@daily" #once a day at midnight
      - BACKUP_ON_START=TRUE #added for testing
      - VALIDATE_ON_START=TRUE #added for testing
      #- POSTGRES_EXTRA_OPTS='--clean --if-exists'
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - BACKUP_DIR=/db_dumps
      - TZ='Europe/London'
    networks:
      - immich
    volumes:
      - /mnt/btrfs_raid2/Backup/Backups/immich_db:/db_dumps
    depends_on:
      - database
    links:
      - database

networks:
  immich:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

volumes:
  model-cache:
```

**Comment by Altycoder** [comment]
All I can see in the portainer log is:

```
2025/03/10 08:59:21 Running version: v0.0.11
2025/03/10 08:59:21 new cron: "@daily"
2025/03/10 08:59:21 Opening port 8080 for health checking
```

**Comment by prodrigestivill** [comment]
Not sure what is the propose of using `env_file`.
But are you aware that you are using both `env_file` and `environment`?
Not sure which one predominates.

Other things it seams not well configured are, missing version image tag of the backup container (please specify the same version as the server, ex: `prodrigestivill/postgres-backup-local:14-alpine`), `POSTGRES_CLUSTER=TRUE` for a single instance server (not sure is appropriate),...

The most important thing is if you are using the `BACKUP_ON_START` or `VALIDATE_ON_START`, please ensure you are using a new version of the image, please ensure to call the `docker compose  pull` to ensure you have the latest build of the image.

**Comment by Altycoder** [comment]
This is the same config that I've been using for months now so whilst I take your points regarding environment vs .env that's not been a problem in the past.  I am using mixed environment variables and .env files on multiple containers no problem (incl the Immich containers above).

I have however tried pasting in the referenced strings from the .env file and removing the .env reference but no difference so it's not that.

I have removed the cluster variable, not sure why I put that there but again it's not been a problem.

Regarding image version, I was using :14 up until recently but removed this so that it defaulted to pulling :latest (which it is doing, it is pulling the new image).  I'm using postgres 'docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52' for immich so I'm guessing that :14 is still correct?

I'm struggling to diagnose the issue as there is no useful log output either from this container at all or anything useful from the postgres container to work with.  This container doesn't output anything but the 3 lines above even though I've added the validate on start and backup on start variables to try and force it to work or at least generate some errors.  

So something fundamental isn't working here all of a sudden which is baffling!?

This doesn't work:

```
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    user: postgres:postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST='database'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='<redacted>'
      - POSTGRES_DB='immich'
      - SCHEDULE='@daily' #once a day at midnight
      - BACKUP_ON_START='TRUE' #added for testing
      - VALIDATE_ON_START='TRUE' #added for testing
      - BACKUP_DIR='/backups'
      - TZ='Europe/London'
    networks:
      - immich
    volumes:
      - /mnt/btrfs_raid2/Backup/Backups/immich_db:/backups
    depends_on:
      - database
    links:
      - database
```
