### ISSUE TITLE
BACKUP_DIR points to a file or folder with insufficient permissions

### ISSUE THREAD

**Issue by Lyannic** [prodrigestivill/docker-postgres-backup-local#168]
I am using `prodrigestivill/postgres-backup-local:12` for three years now and it always worked fine. Today I pulled a new version of that tag. Since then, the container fails starting with the message `BACKUP_DIR points to a file or folder with insufficient permissions.`.

My Docker Compose
```yaml
  db-backupper:
    image: prodrigestivill/postgres-backup-local:12
    restart: always
    user: postgres:postgres
    volumes:
      - /home/api/backups:/backups
    depends_on:
      - db
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: api
      POSTGRES_USER: user
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
```
My host is running Ubuntu 18.04. I double checked with the suggestions from the README (`chown -R 999:999 /home/api/backups`)

These are the permissions of the directory on my host
```
drwxr-xr-x 6       999 docker    4096 Apr  1  2022 backups/
```

So the permissions seem fine for me and the container was also writing to that directly successfully for the past three years. Is it just the validation broken?
