### ISSUE TITLE
ARM: Hanging on healthcheck port open

### ISSUE THREAD

**Issue by yassiezar** [prodrigestivill/docker-postgres-backup-local#18]
Hi, I had this container running for a few days, but noticed that it never made any backups until I manually ran `backup.sh`. It seems that my container is hanging during startup when it tries to open up the healthcheck port. I've tried different ports, but with the same output. I get this when I log into the running container and execute the go-cron job:

    bash-4.4# /usr/local/bin/go-cron -s $SCHEDULE -p $HEALTHCHECK_PORT -- /backup.sh
    2019/03/29 10:00:20 Running version: 
    2019/03/29 10:00:20 new cron: "@daily"
    2019/03/29 10:00:20 Opening port 7654 for health checking

The healtcheck returns the following:

    bash-4.4# curl -f "http://localhost:$HEALTHCHECK_PORT/"
    {
      "Running": {},
      "Last": {
      "Exit_status": 0,
      "Stdout": "",
      "Stderr": "",
      "ExitTime": "",
      "Pid": 0,
      "StartingTime": ""
    },
    "Schedule": "@daily"

My crontab -l returns 

    bash-4.4# crontab -l
    # do daily/weekly/monthly maintenance
    # min	hour	day	month	weekday	command
    */15	*	*	*	*	run-parts /etc/periodic/15min
    0	*	*	*	*	run-parts /etc/periodic/hourly
    0	2	*	*	*	run-parts /etc/periodic/daily
    0	3	*	*	6	run-parts /etc/periodic/weekly
    0	5	1	*	*	run-parts /etc/periodic/monthly

I'm running on an ARM server so I rebuilt the image myself, so I don't know if that maybe makes a difference. I've also tried a version of `go-cron` that doesn't use a healtcheck port, but still no good. Do you have any advice or idea for how I can fix this and get it running?

**Comment by prodrigestivill** [comment]
It looks like an issue with [odise/go-cron](https://github.com/odise/go-cron) in ARM.

How did you build go-cron? In their repository doesn't have binary builds for ARM.

Another option is to use [webdevops/go-crond](https://github.com/webdevops/go-crond), but this is not a drop-in change.

Anyway, I recommend reporting the issue in their repository.

***Note:** `crontab -l` is not reporting any information related with `go-cron`.*

**Comment by yassiezar** [comment]
I tried building go-cron myself on the ARM device in order to get the correct binaries. I also tried with the [michaloo/go-cron](https://github.com/michaloo/go-cron) (the version [odise/go-cron](https://github.com/odise/go-cron) is forked from) which doesn't have a healthcheck port, but it still doesn't work. Sadly, I don't have enough experience in Golang to debug this properly. 

Anyway, I went around the issue by writing a set of scripts to set a cron job to run your backup script on my docker start up instead of using go-cron and its all good now, so I guess this issue can be closed.

**Comment by nicolaibaralmueller** [comment]
> I tried building go-cron myself on the ARM device in order to get the correct binaries. I also tried with the [michaloo/go-cron](https://github.com/michaloo/go-cron) (the version [odise/go-cron](https://github.com/odise/go-cron) is forked from) which doesn't have a healthcheck port, but it still doesn't work. Sadly, I don't have enough experience in Golang to debug this properly.
> 
> Anyway, I went around the issue by writing a set of scripts to set a cron job to run your backup script on my docker start up instead of using go-cron and its all good now, so I guess this issue can be closed.

Hi. I'm experiencing the same issue. Can you explain to me how to workaround this issue?

**Comment by yassiezar** [comment]
For me, the problem was getting the go-cron wrapper compiled and working properly on ARM. A simple fix was to use cron without a wrapper. I followed a similar setup to the one given in [this SO answer](https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container) that basically adds a cron job on the docker's start-up and runs @prodrigestivill 's `backup.sh` script every day

**Comment by nicolaibaralmueller** [comment]
> For me, the problem was getting the go-cron wrapper compiled and working properly on ARM. A simple fix was to use cron without a wrapper. I followed a similar setup to the one given in [this SO answer](https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container) that basically adds a cron job on the docker's start-up and runs @prodrigestivill 's `backup.sh` script every day

Thanks for the reply. Can you show me your edited dockerfile?

**Comment by yassiezar** [comment]
My mildly edited [Dockerfile](https://github.com/yassiezar/server-docker/blob/master/dbbackup/Dockerfile). Relevant lines are from line 20 onwards

**Comment by nicolaibaralmueller** [comment]
> My mildly edited [Dockerfile](https://github.com/yassiezar/server-docker/blob/master/dbbackup/Dockerfile). Relevant lines are from line 20 onwards

Thanks a bunch... so you cloned the git repository. Edited the dockerfile and executed docker compose.

I'm trying to add this into ansible awx installation so the postgres always has a backup and can be restored.

**Comment by nicolaibaralmueller** [comment]
> > My mildly edited [Dockerfile](https://github.com/yassiezar/server-docker/blob/master/dbbackup/Dockerfile). Relevant lines are from line 20 onwards
> 
> Thanks a bunch... so you cloned the git repository. Edited the dockerfile and executed docker compose.
> 
> I'm trying to add this into ansible awx installation so the postgres always has a backup and can be restored.

Thanks a bunch. I will correct the directory in the future.

I'm trying to find the best awx backup/restore strategy and so far tower-cli receive/send is awefull. 
There is git repository awx-migrate which can export credentials with sensitive information but also uses tower-cli.

It would be best to be able to backup the database and restore with a new awx environment BUT what about potential database changes? Will a new awx version installation always work with a different awx version database backup?

**Comment by prodrigestivill** [comment]
I understand that the issue only affects using this container on ARM.
Since the go-cron doesn't work properly on ARM.

I haven't published any version for ARM, but I can lave this issue open to make it more clear that no ARM is currently supported.

**Comment by beckend** [comment]
I have the the exact same issue for x64, using prodrigestivill/postgres-backup-local:alpine

**Comment by prodrigestivill** [comment]
> For me, the problem was getting the go-cron wrapper compiled and working properly on ARM.
Added support for ARM and ARM64 docker images.

> I have the the exact same issue for x64, using prodrigestivill/postgres-backup-local:alpine
Updated go-cron build to use the latest version of [robfig/cron](https://github.com/robfig/cron) and compiled as `static` for the `alpine` tags.

Can anybody check if still happen the reported issues?

**Comment by gerassimos** [comment]
I have the same issue for x64, using the prodrigestivill/postgres-backup-local:10.
I do not understand why the healthcheck does not fail (timeout).
Is anybody using explicit healthcheck on  the docker-compose.yaml (or docker-stack.ayml) ?

The log are:
```log
2020/02/18 11:35:20 Running version: v0.0.8
2020/02/18 11:35:20 new cron: 0 0 0 * * *
2020/02/18 11:35:20 Opening port 8080 for health checking
```

If I execute manually the healthcheck command from within the container I get: 

```bash
root@913ddadb6099:/# curl -f "http://localhost:$HEALTHCHECK_PORT/"
{
  "Running": {},
  "Last": {
    "Exit_status": 0,
    "Stdout": "",
    "Stderr": "",
    "ExitTime": "",
    "Pid": 0,
    "StartingTime": ""
  },
  "Schedule": "0 0 0 * * *"
}
```

**Comment by prodrigestivill** [comment]
Can you try please with a standard cron shedule format (5 items) or one of the [predefined alieses](https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules).

Do you need second precision for the backup?
I can add support for this, but I didn't expect anybody to use it so I didn't enabled it.

**Comment by gerassimos** [comment]
Yes yes of course, I do not need the second precision. 
I just need to use a expression such as "0 0 0 * *".
But I do not understand, I have this configuration for a long time now and it was working and suddenly stop working, what happen?  What change ?

Could be the host OS version ?
On the server which is not working I am using CentOS 7.7
On the server which is working I am using CentOS 7.6
Is the prodrigestivill/postgres-backup-local:10 has change over time? If yes then I suggest to use also a minor version in the tag in order for us to be sure that we always get the same binaries.

I will take the latest image `prodrigestivill/postgres-backup-local:11` and set the cron expression with 5 items. I hope that this will fix my issue.

Following is my actual yml stack file: 

```yml
version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "3"

x-deploy:
  &default-deploy
  replicas: 1
  update_config:
    parallelism: 1
    delay: 10s
  restart_policy:
    condition: on-failure
    max_attempts: 5


services:
  

  db-backup:
    image: prodrigestivill/postgres-backup-local:10
    networks:
      - net-db
    deploy:
      << : *default-deploy
      restart_policy:
        condition: any
        max_attempts: 5
    environment:
      - POSTGRES_HOST=timescaledb
      - POSTGRES_DB=db1
      - POSTGRES_USER=db1
      - POSTGRES_PASSWORD=db1
      - POSTGRES_EXTRA_OPTS=-Fc
        #CRON Expression Format
        # * * * * * *
        # Seconds | Minutes | Hours | Day of month | Month | Day of week
      - SCHEDULE=0 0 0 * * * # every day at 0:00
#      - SCHEDULE=0 * * * * * # every minute
#      - SCHEDULE=@daily # This is also a valid entry
      - BACKUP_KEEP_DAYS=1
      - BACKUP_KEEP_WEEKS=1
      - BACKUP_KEEP_MONTHS=1
    volumes:
      - db-backup:/backups
    logging: *default-logging
  

volumes:
  db-data:
  db-backup:

networks:
  net-db:

```
