### ISSUE TITLE
Container stopped (exit 0) with NO reason

### ISSUE THREAD

**Issue by gerassimos** [prodrigestivill/docker-postgres-backup-local#20]
I am running this as service with restart policy "on-failure", at the begging the service is reported as running (Replicas 1/1) after a while the service is reported as not running (Replicas 0/1).  

The "docker stack ps app" is reporting the state "Shutdown"
```console
# docker stack ps app                                                                   
ID             NAME              IMAGE                                       DESIRED STATE  CURRENT STATE                ERROR                              PORTS
v86mt8uk5og7   app_db-backup.1  prodrigestivill/postgres-backup-local:10     Shutdown       Complete 6 hours ago
````
The `docker ps -a` is reporting the state "Exited (0) 6 hours ago"
```console
# docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED         STATUS                   PORTS       NAMES
32dfc96fbb2a        prodrigestivill/postgres-backup-local:10    "/bin/sh -c 'exec /u…"   7 hours ago     Exited (0) 6 hours ago               app_db-backup.1.v86mt8uk5og7x7su91gshyg7q
```

Following are the logs of the container
```console
[root@GDN-S-GNSS2 ~]# docker container logs 32dfc96fbb2a
2019/07/01 06:39:37 Running version: 6f160c2
2019/07/01 06:39:37 new cron: 0 0 0 * * *
2019/07/01 06:39:37 Opening port 8080 for health checking
(0x7f8a23c161d8,0xf)
2019/07/01 06:54:59 Stopping
2019/07/01 06:54:59 Waiting
2019/07/01 06:54:59 Exiting
```

**Comment by prodrigestivill** [comment]
I tried to run the same image with the same SCHEDULE for a long period of time without any issues.

For your logs (see reference below) looks like some program killed it with either SIGINT or SIGTERM.
Maybe the docker limits set are too restricted and either docker or kernel killed it.
Try to put higher limits and try again.

_As a reference, here are the reference to the code in order to proceed to stop: [go-cron.go#L42](https://github.com/odise/go-cron/blob/v0.0.7/bin/go-cron.go#L42)_

_And matches with this message:_
> ```
> (0x7f8a23c161d8,0xf)
> 2019/07/01 06:54:59 Stopping
> ```

**Comment by gerassimos** [comment]
Thank you very much for your answer!!
I do not have any resource limits in place.
It does not happen all the times to me also. I have many severs running the same docker stack and only in some of them this issue occurs.

Is there anything that I can do with the log message "(0x7f8a23c161d8,0xf)" to understand which process send the SIGINT or SIGTERM signal ?

Could be the case that the web server is not started properly and so the health check fails but instead of exiting with exit_code =1 , it exists with exit_code = 0
Ref:
https://github.com/odise/go-cron/blob/v0.0.7/httpserver.go#L15
I am just guessing, I am not familiar with the go language.

The service is stopped (and is not restarted) because I have a restart policy set to on-failure. As a quick (and dirty) fix I will try to set the restart policy to "always". What you thing ?

Following is the section of the docker-stack file related to the `db-backup` service 
```yml
db-backup:
    image: prodrigestivill/postgres-backup-local:10
    networks:
      - net-db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      - POSTGRES_HOST=timescaledb
      - POSTGRES_DB=${APP_DB:-app_db}
      - POSTGRES_USER=${APP_DB_USER:-app_db}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD:-app_db}
      - POSTGRES_EXTRA_OPTS=-Fc
        #CRON Expression Format
        # * * * * * *
        # Seconds | Minutes | Hours | Day of month | Month | Day of week
      - SCHEDULE=0 0 0 * * * # every day at 0:00
#      - SCHEDULE=0 * * * * * # every minute
#      - SCHEDULE=@daily # This is also a valid entry
      - BACKUP_KEEP_DAYS=1
      - BACKUP_KEEP_WEEKS=1
      - BACKUP_KEEP_MONTHS=1
    volumes:
      - db-backup:/backups
    logging: *default-logging
````
Thank you again for your help!!

**Comment by derakhshanfar** [comment]
I have the same issue, could you find a solution? @gerassimos

**Comment by gerassimos** [comment]
Yes. If you set the restart policy condition to "any" this will somehow solve the issue by creating a new container each time this strange exit (0) situation occurs. But this is just a workaround, the proper solution is to fix what cause the process to exit (0). 

```yml
...
deploy:
    restart_policy:
        condition: any
...
```

@prodrigestivill
I thing this issue could be a bug of the "odise/go-cron" project.
Maybe I should open the same issue on the "odise/go-cron" project also. What you think??

Happy that I am not the only one having this problem :-)

**Comment by derakhshanfar** [comment]
Thanks so much for your answer and I'm happy to. I agree we ought to open this issue on "dise/go-cron".
could you find a log error for reopening this issue over there?
@gerassimos

**Comment by gerassimos** [comment]
@prodrigestivill
Unfortunately the "Issues " section is not enabled on the "odise/go-cron" project. I do not know how to notify the contributors of the project.

The log messages in my environment are the following:
```console
[root@GDN-S-GNSS2 ~]# docker container logs 32dfc96fbb2a
2019/07/01 06:39:37 Running version: 6f160c2
2019/07/01 06:39:37 new cron: 0 0 0 * * *
2019/07/01 06:39:37 Opening port 8080 for health checking
(0x7f8a23c161d8,0xf)
2019/07/01 06:54:59 Stopping
2019/07/01 06:54:59 Waiting
2019/07/01 06:54:59 Exiting
```

**Comment by prodrigestivill** [comment]
Can you both try to disable the health check from the container, if this solves the issue, so maybe is some issue with go-cron and health checking.

If this is the case we can disable the health check in general.

Example of docker-compose to disable health checking:
```yml
db-backup:
    image: prodrigestivill/postgres-backup-local:10
    healthcheck:
        disable: true
    # ...
```
