### ISSUE TITLE
Question: What is the POSTGRES_HOST

### ISSUE THREAD

**Issue by Jackbaude** [prodrigestivill/docker-postgres-backup-local#42]
Im new to docker and databases and im quite confused what the POSTGRES_HOST value should be. I kept getting hung on listening for post 8080 and I think this is issue because it is not able to connect. Thank you for any help!

**Comment by sigrlami** [comment]
That's the name of your container where PostgreSQL running, I usually call them `<app-name>-db`. For example, look how name `stremma-ai-db` shows up on docker-compose.yaml:

```
  stremma-ai-db:
    environment:
     - POSTGRES_PASSWORD=myawesomepass
     - POSTGRES_USER=myuser
     ... 
    pgbackups:
        image: prodrigestivill/postgres-backup-local
        restart: always
        user: postgres:postgres
        volumes:
            - /var/opt/pgbackups:/backups
        links:
            - stremma-ai-db
        depends_on:
            - stremma-ai-db
        environment:
            - POSTGRES_HOST=stremma-ai-db
            - POSTGRES_DB=database_name_inside_streamm-ai-db
        ....    
```
