### ISSUE TITLE
Question about "/var/lib/postgresql/data" volume

### ISSUE THREAD

**Issue by steakhutzeee** [prodrigestivill/docker-postgres-backup-local#53]
Hi, have a little question.

I have actually this compose file:

```
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    container_name: paperless-ng_db_bak
    restart: unless-stopped
    user: 1000:100
    volumes:
      - /srv/dev-disk-by-label-HC2/AppData/paperless-ng_db_bak/backups:/backups
      - pgbackups_data:/var/lib/postgresql/data
    depends_on:
      - db
    environment:
      - TZ=Europe/Rome
      - POSTGRES_CLUSTER=TRUE
      - POSTGRES_HOST=paperless-ng_db
      - POSTGRES_DB=xxx
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_EXTRA_OPTS=
      - SCHEDULE=@midnight
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=0
      - BACKUP_KEEP_MONTHS=0
```

I checked performing a manually backup and it works. 

I just don't understand why a new volume is created with the container, pointing to `/var/lib/postgresql/data`. In my compose file i called the volume `pgbackups_data` just to recognize it. 

Thank you in advance!
